name: Sign & Release Test

run-name: Sign & Release Test

# Trigger workflow manually
on:
  workflow_dispatch:


jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{secrets.GPG_KEY}}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish To OSSRH (Maven Central Staging)
        run: |
            mvn org.apache.maven.plugins:maven-gpg-plugin:3.2.4:sign-and-deploy-file \
                --batch-mode \
                -e \
                -Dfile=./tinkar-starter-data-reasoned-1.0.0-pb.zip \
                -DpomFile=./tinkar-starter-data-reasoned-1.0.0.pom \
                -Dclassifier=pb \
                -Durl="https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/" \
                -DrepositoryId=ossrh \
                -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}} \
                -Dpinentry-mode \
                -Dloopback \
                -Dyes \
                -Dverbose
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_TOKEN_USER}}
          MAVEN_CENTRAL_TOKEN: ${{secrets.OSSRH_TOKEN_PASS}}
          MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}