name: Sign & Release Test

run-name: Sign & Release Test

# Trigger workflow manually
on:
  workflow_dispatch:


jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{secrets.GPG_KEY}}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish To OSSRH (Maven Central Staging)
        run: |
            ./mvnw deploy \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -DskipTests \
                -DskipITs \
                -Dmaven.main.skip \
                -Dmaven.test.skip \
                -DrepositoryId=ossrh \
                -DrepositoryIdOSSRH='true' \
                -PstageOSSRH
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_TOKEN_USER}}
          MAVEN_CENTRAL_TOKEN: ${{secrets.OSSRH_TOKEN_PASS}}
          MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}